content/_guides/channels.md

The older /cs ACCESS #channel LIST does not work on libera.chat.

channels.md: Replace ACCESS LIST with FLAGS

---

chanreg.md

It looked like the text in `[]` was intended to be anchor links, so now they are.

Fix anchor links in chanreg.md

---

content/_guides/sasl/irssi.md

ssl is the older protocol, irssi is fine with tls

change ssl argument to tls

---

content/_guides/clients.md

Adds a full stop here, removes a repetition there and corrects the
spelling of WeeChat.

Fix typos in /guides/clients

---

content/_guides/certfp.md

While sha512sum *is* mentioned at the top of the page at inspecting-your-certificate, this can be easily overlooked for someone who already has a certificate set up and is just looking to add it in libera, and might skip down to the add-your-fingerprint-to-nickserv section.

Highlight sha512 certfp usage

---

content/_guides/sasl/hexchat.md

Several users on #libera noticed this defaults to plaintext. It is the only
client guide that does so.

Use TLS when adding a server to HexChat

---

README.md

- Correctly capitalise nouns and acronyms
- Mention nicknames and user modes in examples of things that should be
quoted as code
- Use the Oxford comma
- Recommend a 78-column wrapping to make editing in 80-column terminals
easier
Re-wrap to this
- Avoid referring to able-bodied graphical users as "normal"
- Because there are multiple licenses, rename the License header
- Abbreviate the Creative Commons license to CC BY-NC-SA, as this is the
recommended presentation:
https://creativecommons.org/licenses/by-nc-sa/4.0/

README.md: Several minor fixups

---

content/_guides/clients.md

The client name includes "IRC".
Add link to its source repo on github.

Update name and links for RevolutionIRC

---

content/_guides/connect.md

`hidden service` was the formal term, we are using `onion service` in all Tor
documentation as mentioned in the URL below.
https://2019.www.torproject.org/docs/onion-services.html.en

Uses onion service as technical term for Tor service

---

Gemfile
Gemfile.lock

Fixes #96. I tested it with Ruby 3 and 2.7, both worked fine.

Explicitly add webrick into the Gemfile

---

content/_guides/sasl.md

The section below is not visible on the sidebar or on initial page load
without scrolling. This makes it easy to miss.

Make SASL requirement clearer

---

content/_guides/sasl/irssi.md

Hi, suggesting some comments about this issue with irssi and SASL, which affects Debian buster (stable) and stretch (oldstable) right now, at least.

Add information regarding irssi CVE-2019-13045

---

content/_guides/registration.md

For the sake of linking to "how to log in" from other pages without
the cruft of registering again (or people will register multiple times)

Add manual logging in to "logging in"

---

content/_guides/sasl.md

Webchat is no longer exempt from the sasl-only requirements due to
repeated abuse on said ranges. We do apologise for the inconvenience.

Update documentation regarding sasl-only & webchat

---

content/_guides/faq.md

It's giving HTTP 404 as `/guides/guides/sasl` doesn't exist, this should fix it.

Fix a broken URL in FAQ

---

content/_guides/clients.md

The current clients page is a bit of a mess with who it's for and what clients are listed. This rewrites the page to focus only on first-time IRC users to easily choose a client.

Redo clients page to focus on first-time users

---

_config.yml

Fixed #85 
As per issue #85 - currently pages do not work if you add a trailing slash. The extremely simple solution for this is to make a one character change to `config.yml`.
`- permalink: /:name`
to:
`- permalink: /:name/`
This will ensure that all pages work both with *and* without a trailing slash. It does not break any of the existing layout and no further changes would be required to support this. I have tested every link on the site and none are broken as a result.

Fixes #85 -- change config so that all pages work with trailing slash

---

404.md

I think my previous pull request, #131, led to GitHub pages not automatically recognising 404.md as the 404 page. This change will fix it so that the Libera 404 page is used, instead of the GitHub Pages default 404 page, which is currently being served.

Add permalink for 404.md to make GitHub pages serve it

---

.github/workflows/lint.yml

Various urls, especially those generated by jekyll SEO must be absolute
urls, e.g. the canonical tag.
If adding a new page, this is unfortunate. This change ensures
htmlproofer considers external references to our domain as internal
links.
See also https://github.com/gjtorikian/html-proofer/issues/170

Convert full path urls to internal links in lint

---

content/_guides/sasl/weechat.md

originally submitted as
https://github.com/freenode/web-7.0/commit/5c6b40aa563142df20b44b1b0fa6ac28cf3374f9
also updates network name to `libera` instead of `liberachat`

add /secure recommendation

---

content/_guides/findingchannels.md

Previously, the help text for `/msg alis help list` was copied out of an opered connection and therefore mentioned oper-only options (`-showsecret`). Replace with the most recent version of the user-facing help. Some spacing changes seem to have been made in the alis output; these were maintained as well in this PR.

Show user-facing help for alis

---

policies.md

Update our nickname expiry policy from 10 to 20 weeks in the routine
case.

Extend nickname expiration to 20 weeks

---

content/_guides/usermodes.md

Now our example at the top shows how to set +w, would it be better with another example now that +w is always set?

Update documentation to state +w is set by default

---

_data/channelmodes.yml

The lack of paragraph separation between made it look like forwards are only supported for extbans at first glance.

Make clearer that forward bans work with any ban.

---

content/_guides/certfp.md
content/_guides/sasl.md
content/_guides/sasl/emacs-erc.md
content/_minutes/2021-12-17-mgm-minutes.md

The SASL guides are "how to set up SASL on your client" and not "how to
set up your client from scratch" -- we assume people have a working
client and just need to enable SASL on it. As such, eliminate much of
the wording in the ERC guide that has absolutely nothing to do with
SASL.
The ERC guide and a handful of other pages were modified in order to
conform to the style guide and fix up some links that caused
redirections (and therefore htmlproofer fails).

Edit ERC guide for brevity and make CI happy

---

content/_guides/sasl.md
content/_guides/sasl/catgirl.md

Adds SASL instructions for [catgirl](https://git.causal.agency/catgirl/about/), a cute and opinionated TUI IRC client.
(I ran the instructions past the client author before PRing, she says they look fine. I have not built the website locally to make sure they're formatted correctly.)

Add SASL instructions for catgirl

---

content/_guides/certfp.md

For Konversation, the Identities window accessed through Settings has an `Auto Identify` section.
Just a nitpick. Appreciate the documentation a lot.

A typo in certfp.md

---

content/_posts/2021-12-20-end-of-2021-review.md
content/_posts/2022-05-19-happy-birthday-libera-chat.md

the first blog post uses `staff`. i think we should avoid using `Libera` instead of `Libera Chat`, and i think naming which staff are writing a blog post is redundant given it's on our site

make collective staff authorship use a uniform name

---

_includes/head.html

This helps feed discoverability for compatible clients, allowing a user for example to point an RSS reader directly to the website.
Some browsers also detect the feed automatically.

Add Atom link tag in head

---

_includes/article.html

fix whitespace being considered part of <a> in blog post permalinks

---

content/_guides/faq.md

It seems the old terms of service link broke at some point but was hidden within the other noise in htmlproofer's link checker. Update to the new document.

Fix link to EMS ToS

---

.github/workflows/lint.yml

liberapay rejects the link liveness check with a 403. While we could spoof the User-Agent to bypass this, it seems better to respect their wishes to block these automated processes and just not bother checking the link in the first place.
Not sure what the issue is with imy.se, but ignore that too as it seems to be an issue with the TLS handshake (?) despite the link working fine in a browser.

Ignore perpetually broken URL checks

---

_includes/inline-style.css

CCS Text Level 4's [text-wrap balance](https://drafts.csswg.org/css-text-4/#text-wrap) is starting to roll out in [browsers](https://developer.chrome.com/blog/css-text-wrap-balance/), whilst not available in stable versions yet it's nice to be ready to have BALANCED HEADINGS!!!!

Add `text-wrap: balance;` to headings

---

content/_guides/faq.md

We've got a way to do this for all clients now which is frequently mentioned in `#libera` and such. While someone was asking about just this, I had trouble finding a guide to link it to them and noticed this outdated blurb.

faq.md: mention NickServ BADPASSWDMSG in place of outdated info

---

content/_posts/2023-06-07-matrix-irc-bridge-updates.md

Since publishing this blog, EMS have set up an issue tracker specifically for bridge support. 
This PR updates the blog to reflect that.

replace link to ems support 

---

content/_guides/helpers.md

"Operator" is not a proper noun, grammatically, and psychologically, capitalizing it gives an unhelpful impression of "Operator Superiority"

Update helpers.md to s/Operator/operator/

---

content/_posts/2023-07-03-matrix-deportalling.md

It's far from obvious, so multiple people have asked about it on #libera-matrix.

Add link to the portal/plumbed documentation

---

content/_guides/clients.md

While the goal of the list is not to be exhaustive, Goguma is a simple and intuitive client that can be a great choice for new IRC users on Android.

Add the Goguma Android IRC client

---

chanreg.md
content/_guides/cloaks.md

The current page is unclear and confusing in many respects. This overhaul tightens up the wording and clarifies some common points of confusion people have regarding registering channels and groups on libera.

Overhaul chanreg

---

_includes/nav.html

This is being tested by browsers (safari, edge, opera in preview. Stable in chrome 120) to create a native "accordion" effect only allowing one `<details>` element with the same name attribute to be open at a time

Add name="" attribute to <details> element in main navigation

---

content/_guides/certfp.md

Weechat 4.0.0 renamed the ssl_* options to tls_*. Update the guide page accordingly.
For reference, please see the Weechat 4.0.0 release notes: https://blog.weechat.org/post/2023/06/24/Version-4.0.0
> Options changed:
> 
>     option irc.server_default.ssl renamed to irc.server_default.tls
>     option irc.server_default.ssl_cert renamed to irc.server_default.tls_cert
>     option irc.server_default.ssl_dhkey_size renamed to irc.server_default.tls_dhkey_size
>     option irc.server_default.ssl_fingerprint renamed to irc.server_default.tls_fingerprint
>     option irc.server_default.ssl_password renamed to irc.server_default.tls_password
>     option irc.server_default.ssl_priorities renamed to irc.server_default.tls_priorities
>     option irc.server_default.ssl_verify renamed to …

Update weechat certfp guide commands for weechat v4.0.0

---

content/_guides/clients.md

- Remove Hexchat (no longer maintained)
- Update Konversation (no longer supports Windows)
- Add Quassel
- Update Goguma (now has iOS client)

Update client list

---

policies.md

As per @skizzerz in [PR#358](https://github.com/Libera-Chat/libera-chat.github.io/pull/358#discussion_r1608569210), this change needs to be in it's own PR as all changes to policy, even typographical ones, require formal staff discussion and vote at a monthly meeting.

modifying spelling to be en_GB as per style guide

---

content/_guides/sasl/hexchat.md

changed in 2.16.2: https://github.com/hexchat/hexchat/commit/9b76b557ecaece2a5fa862ea4dc75ed613e3fbf0#diff-b519a608764ab820661094eb3801e529041ddec29104172896053d389de50d0aR152

hexchat login method label is "SASL PLAIN"

---

content/_guides/cloaks.md

Occasionally we get old users who registered prior to auto-cloaking contacting staff asking why they don't have cloaks.
This should clarify that auto-cloaking happens to newer accounts, and also cleans up a few bits of wording.

Clarify generic user auto-cloaking

---

.github/workflows/jekyll-build.yml

Fixes pages not building on ubuntu-latest due to an ancient version of setup-ruby. Also bumps Ruby version 3.0 -> 3.3.

Use latest ruby/setup-ruby action

---

content/_guides/memo.md

Closes #348 
This PR adds a guide for MemoServ, with information taken from MemoServ's `HELP`. To make things easier for prospective users, I've put all commands into a guide rather than just mentioning the tool's existence so that users can refer back to it. Let me know if this isn't wanted.

Add MemoServ guide

---

chanreg.md
content/_guides/cloaks.md
content/_guides/creatingchannels.md
content/_guides/groupcontacts.md

Add GC guide

---

content/_guides/certfp.md

This adds directions for mIRC to do certfp.
In the third direction you click a icon (in image below), I'm not what exactly to call it, so I included both descriptions.

certfp.md: Add mIRC

---

content/_guides/connect.md
content/_guides/faq.md

1. Make the CA root cert path monospace to be consistent with the other guides which use monospace for paths.
2. Add missing terminal punctuation in body.
3. Add missing terminal punctuation in section heading. Yes, the anchor stays the same.

minor terminal punctuation fixes and monospace

---

content/_guides/creatingchannels.md

Expecting people to actually do the help command to see how to add the
flags doesn't really work. Added an example for giving +v, as that is
less footgun than +o if given to the wrong person while experimenting.

Rearrange "Setting up permissions" and add another example
