- _data/nav.yml
- bylaws.md
These are the initial version of the Libera Chat Bylaws which should partly address #18.
As mentioned in #18 some changes to these are expected shortly to clarify some intended meanings.
> Add Bylaws

- content/_guides/connect.md
https://support.torproject.org/about/why-is-it-called-tor/
> _guides/connect.md: fix spelling of Tor

- content/_guides/channelmodes.md
> jekyll backend liquid query for channel modes excludes restricted

- content/_guides/connect.md
We now have the US & EU region-specific rotations, so can mention them here.
> Add EU & US region rotations to connect doco

- .github/workflow-support/htmlproofer-matcher.json
- .github/workflows/lint.yml
- Gemfile
- Gemfile.lock
- _includes/hero.html
- _includes/nav.html
- content/_guides/sasl.md
- content/_guides/sasl/chatzilla.md
> GitHub action on PR: htmlproofer

- content/_guides/bots.md
Recreation of #70 because I did an oops
This is the first draft of 2 of our public bots
Fixes #65
> adding bot documentation

- _data/nav.yml
- contributing/development.md
- contributing/sponsor.md
Just putting this here for the time being, since its tidier to have all the discussion in here.
This PR would add sponsor.md and development.md. sponsor.md details the requirements of people who want to donate a server, it will probably be expanded by someone else at a later date, but monetary donations are not yet up.
development.md details how everyone with a bit of time can help us out.
> New contributing docs

- chanreg.md
Update our public policies according to the meeting, mainly with regards to primary / secondary contacts. 
Also update the cloak format since we forgot to update the public docs about it, oops.
> Update our public policies according to the meeting, mainly with regards to primary / secondary contacts

- content/_guides/bots.md
Now it's only necessary to /invite litharge and litharge will explain the procedure
> Simplify the setup to request litharge

- _includes/footer.html
Conflicts:
_includes/footer.html
> Make intra-site links site-relative

- content/_guides/webchat.md
> Add a guide for the webchats (#121)

- content/_guides/cloaks.md
> Add a guide on cloaks

- content/_guides/certfp.md
- content/_guides/cloaks.md
- content/_guides/faq.md
"also" was out of place and "viewingthe", "everthing" and "sinply" are not words.
> Fix typos/wording

- content/_guides/faq.md
> Add faq for how to find staff

- content/_guides/catalyst.md
- content/_guides/helpers.md
adds catalyst.md for opers and ops
adds helpers.md for regular helpful folk
> Catalyst and helper guides

- content/_guides/creatingchannels.md
The page is pretty much entirely rewritten. It should be actually useful now!
I also yoinked the attribution to web-7.0 because it was not derived from
that site.
> Rewrite creatingchannels.md

- _config.yml
> add minutes feed

- _includes/article.html
> fix archive link

- _config.yml
- content/_minutes/2021-07-27-mgm-minutes.md
- minutes.html
> show excerpt on minutes index page

- content/_guides/catalyst.md
> Mention cross-channel drama in catalyst.md

- content/_guides/webchat.md
I apparently forgot to mention this in the guide.
Also tweak wording about lost users.
> Add advice about +r to webchat.md

- content/_guides/cloaks.md
Also fixes the list at the bottom of the page because it created `<p>`'s inside each `<li>` which added margin to the block start and end. became one PR because GitHub web
> Cloaks: better explain how to obtain a bot cloak

- _includes/guides-aside.html
- content/_guides/bots.md
- content/_guides/catalyst.md
- content/_guides/certfp.md
- content/_guides/channelmodes.md
- content/_guides/channels.md
- content/_guides/clients.md
- content/_guides/cloaks.md
- content/_guides/connect.md
- content/_guides/creatingchannels.md
- content/_guides/extbans.md
- content/_guides/faq.md
- content/_guides/findingchannels.md
- content/_guides/helpers.md
- content/_guides/registration.md
- content/_guides/sasl.md
- content/_guides/sendpass.md
- content/_guides/usermodes.md
- content/_guides/webchat.md
- guides.md
weight sorting added to category queries in menu and page.
weights increments of 10, to enable easier adding of new content
about-irc category starts at 20 to account for new page in #161.
> Add weighting to guides

- _config.yml
- content/_guides/faq.md
- index.md
addresses #164 but i was unable to set up BreadcrumbLists
> add default json-ld types

- about.md
Prioritize /stats p, point at the FAQ for other methods
> Update about.md re: finding staff

- contributing/development.md
:point_right::sunglasses::point_right:
> mention ircrobots on contributing/development.md

- content/_minutes/2021-12-17-mgm-minutes.md
(this space intentionally left blank)
> Add minutes for december 2021

- content/_guides/bots.md
> guides/bots: mention that litharge needs the ability to op itself

- about.md
'Either' implies two, and there are three teams
> tweak wording

- content/_guides/sasl.md
> Disambiguate SASL and SSL/TLS

- privacy.md
periclase will be deployed soon, which collects (but currently does not store) CTCP VERSION information from clients. Explicitly mention this collection in the privacy policy. Additionally, ensure the abuse protection purpose clearly states that information is processed to protect the staff, users, and services (as opposed to some subset of those things).
> Update privacy policy

- .github/FUNDING.yml
should cause there to be a button like this 
on this repo
> add .github/FUNDING.yml

- content/_guides/clients.md
Adds Pidgin to the list of desktop clients. Resolves https://github.com/Libera-Chat/libera-chat.github.io/issues/132.
> Adds pidgin client.

- content/_posts/2023-01-13-login-failure-notice.md
merge once changes are deployed
todo: change date on filename when we decide to merge this
> draft login failure notice blog post

- _includes/article.html
show current year
also added permalink to posts
> Permalink to articles

- content/_guides/faq.md
This kind of question is asked almost daily, so let's direct people directly to the places where EMS can help them.
> Add paragraph about issues that #libera-matrix cannot help with

- content/_posts/2024-07-03-zncpsa.md
add advice on how to actually unload the module, and also correct some grammar that scanned badly when i first read the post.
> couple of touchups to the ZNC PSA

- content/_guides/certfp.md
Not sure if this requires a note in the certificate generation section to avoid users needlessly creating certs manually.
> document certfp auth via soju

- content/_guides/clients.md
> Note that paid IRCCloud users can use non-IRCCloud clients
